<?php

return [
    'a', 'actualmente', 'acuerdo', 'adelante', 'ademas', 'además', 'adrede',
    'afirmó', 'agregó', 'ahi', 'ahora', 'al', 'algo', 'alguna', 'algunas',
    'alguno', 'algunos', 'alla', 'alli', 'allí', 'alrededor', 'ambos', 'amen',
    'ante', 'antes', 'apenas', 'aproximadamente', 'aquel', 'aquella',
    'aquellas', 'aquello', 'aquellos', 'aqui', 'aquí', 'arriba', 'asi',
    'así', 'atras', 'aun', 'aunque', 'ayer', 'bajo', 'bastante', 'bien',
    'breve', 'buen', 'buena', 'buenas', 'bueno', 'buenos', 'cada', 'casi',
    'cerca', 'cierta', 'ciertas', 'cierto', 'ciertos', 'cinco', 'claro',
    'com', 'como', 'con', 'conmigo', 'consigo', 'contigo', 'contra', 'cual',
    'cuales', 'cualquier', 'cuando', 'cuanto', 'cuatro', 'cuya', 'cuyas',
    'cuyo', 'cuyos', 'da', 'de', 'debajo', 'debe', 'deben', 'debido',
    'decir', 'del', 'demas', 'demás', 'dentro', 'des', 'desde', 'despues',
    'después', 'detras', 'detrás', 'dia', 'días', 'dice', 'dicen', 'dijo',
    'donde', 'dos', 'durante', 'e', 'el', 'él', 'ella', 'ellas', 'ellos',
    'en', 'encima', 'entonces', 'entre', 'era', 'eras', 'eramos', 'eran',
    'eres', 'es', 'esa', 'esas', 'ese', 'eso', 'esos', 'esta', 'estaba',
    'estado', 'estamos', 'estan', 'están', 'estar', 'estas', 'este', 'esto',
    'estos', 'estoy', 'etc', 'fue', 'fuera', 'fueron', 'fui', 'gran', 'ha',
    'hace', 'hacia', 'han', 'has', 'hasta', 'hay', 'he', 'her', 'hoy',
    'hubo', 'igual', 'incluso', 'jr', 'la', 'las', 'le', 'les', 'lo',
    'los', 'luego', 'mas', 'más', 'mayor', 'me', 'mediante', 'menos',
    'mientras', 'mismo', 'mi', 'mis', 'mio', 'mío', 'mios', 'míos',
    'mucho', 'muchos', 'muy', 'nada', 'ni', 'ninguna', 'ninguno',
    'no', 'nos', 'nosotras', 'nosotros', 'nuestra', 'nuestras', 'nuestro',
    'nuestros', 'nuevo', 'nunca', 'o', 'os', 'otra', 'otras', 'otro',
    'otros', 'para', 'parece', 'pero', 'poco', 'por', 'porque', 'primer',
    'primera', 'puede', 'pueden', 'que', 'qué', 'quien', 'quienes', 'quién',
    'se', 'sea', 'según', 'ser', 'si', 'sí', 'siendo', 'sin', 'sobre',
    'son', 'su', 'sus', 'también', 'tampoco', 'tan', 'tanto', 'te',
    'tenemos', 'tiene', 'tienen', 'todavia', 'todavía', 'todo', 'todos',
    'tras', 'tu', 'tú', 'tus', 'un', 'una', 'uno', 'unos', 'usted',
    'ustedes', 'vez', 'vosotras', 'vosotros', 'vuestra', 'vuestras',
    'vuestro', 'vuestros', 'y', 'ya', 'yo',
];
